### ISSUE TITLE
[Log] 통계 API 개발

### ISSUE THREAD

**Issue by gyus13** [preonboaring-be-team-k/user-role-blog-service#17]
### Issue 타입(하나 이상의 Issue 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 그 외

### 상세 내용
* 통계 파라미터 추가

* Swagger API 추가

**Comment by minenam** [comment]
#51 로 Merge 완료
